src/main/java/com/realdolmen/thomasmore/domain/Support.java
package com.realdolmen.thomasmore.domain;

import javax.persistence.DiscriminatorValue;
import javax.persistence.Entity;
import javax.persistence.OneToMany;
import java.util.ArrayList;
import java.util.List;

@Entity
@DiscriminatorValue("Support")
public class Support extends User {

    public Support() {
    }

    public Support(String email, String firstName, String lastName, String password) {
        super(email, firstName, lastName, password);
    }

    @OneToMany(mappedBy = "support")
    private List<Ticket> tickets = new ArrayList<Ticket>();

    public List<Ticket> getTickets() {
        return tickets;
    }

    public void setTickets(List<Ticket> tickets) {
        this.tickets = tickets;
    }
}

src/main/java/com/realdolmen/thomasmore/controller/TicketController.java
package com.realdolmen.thomasmore.controller;


import com.realdolmen.thomasmore.domain.*;
import com.realdolmen.thomasmore.security.UserSession;
import com.realdolmen.thomasmore.service.*;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.core.userdetails.UserDetails;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;


@ManagedBean
@SessionScoped
public class TicketController {

    @ManagedProperty("#{customerService}")
    private CustomerService customerService;

    @ManagedProperty("#{supportService}")
    private SupportService supportService;

    @ManagedProperty("#{encryptionService}")
    private EncryptionService encryptionService;

    @ManagedProperty("#{userService}")
    private UserService userService;

    @ManagedProperty("#{mailService}")
    private MailService mailService;

    @ManagedProperty("#{orderService}")
    private OrderService orderService;

    @ManagedProperty("#{ticketService}")
    private TicketService ticketService;

    private List<Order> orders = new ArrayList<>();
    private Order order;
    private String orderId;
    private String message;
    private Ticket ticketDetails;
    private String description;
    private String answer;
    private String subject;
    private String status;

    private List<Ticket> newTickets = new ArrayList<>();
    private List<Ticket> openTickets = new ArrayList<>();
    private List<Ticket> onholdTickets = new ArrayList<>();
    private List<Ticket> solvedTickets = new ArrayList<>();


    public Customer getLoggedinCustomer() {
        Object principal = SecurityContextHolder.getContext().getAuthentication().getPrincipal();
        String email = ((UserDetails) principal).getUsername();
        Customer customer = customerService.findByEmail(email);
        return customer;
    }

    public Support getLoggedinSupport() {
        Object principal = SecurityContextHolder.getContext().getAuthentication().getPrincipal();
        String email = ((UserDetails) principal).getUsername();
        Support support = supportService.findByEmail(email);
        return support;
    }

    public void getOrdersByCustomer(Customer customer) {
        orders = orderService.getOrdersByCustomersEmail(customer.getEmail());
    }

    public String customerTicket() {
        Customer customer = getLoggedinCustomer();
        getOrdersByCustomer(customer);
        return "/customer/ticket.xhtml?faces-redirect=true";
    }

    public String saveTicket() {
        Customer customer = getLoggedinCustomer();
        Ticket ticket = new Ticket();
        order = orderService.get(Long.parseLong(orderId));
        if (order.getCustomer().getId() == customer.getId()) {
            ticket.setOrder(order);
            ticket.setDescription(description);
            ticket.setDate(new GregorianCalendar());
            ticket.setStatus(Ticket.Status.NEW);
            ticketService.saveTicket(ticket);
            setMessage("Uw ticket is ingestuurd en we zullen hier zo spoedig mogelijk op antwoorden.");
            return "ticketconfirmation.xhtml?faces-redirect=true";
        } else {
            setMessage("Er is mogelijk iets mis gegaan tijdens het versturen van uw ticket, gelieve dit opnieuw te proberen.");
            return "ticketconfirmation.xhtml?faces-redirect=true";
        }
    }

    public String supportTicketLists() {
        Support support = getLoggedinSupport();
        newTickets = ticketService.findByStatus(Ticket.Status.NEW);
        openTickets = ticketService.findBySupportAndStatus(support, Ticket.Status.OPEN);
        onholdTickets = ticketService.findBySupportAndStatus(support, Ticket.Status.ON_HOLD);
        solvedTickets = ticketService.findByStatus(Ticket.Status.SOLVED);
        return "ticket.xhtml?faces-redirect=true";
    }

    public String changeStatus(String statusOut, Ticket ticket) {
        switch (statusOut) {
            case "open":
                ticket.setStatus(Ticket.Status.OPEN);
                break;
            case "onhold":
                ticket.setStatus(Ticket.Status.ON_HOLD);
                break;
            case "solved":
                ticket.setStatus(Ticket.Status.SOLVED);
                break;
        }
        Support support = getLoggedinSupport();
        ticket.setSupport(support);
        ticketService.saveTicket(ticket);
        return supportTicketLists();
    }

    public String getTicketDetails(Ticket ticket) {
        ticketDetails = ticket;
        switch (ticket.getStatus()) {
            case NEW:
                status = "NIEUW";
                break;
            case OPEN:
                status = "OPEN";
                break;
            case ON_HOLD:
                status = "IN WACHT";
                break;
            case SOLVED:
                status = "OPGELOST";
                break;
            case PENDING:
                status = "IN AFWACHTING";
                break;
        }
        return "ticketdetails.xhtml?faces-redirect=true";
    }

    public String sendReply(Ticket ticket) {
        Support support = getLoggedinSupport();
        SimpleDateFormat dt1 = new SimpleDateFormat("yyyy-MM-dd");
        String date = dt1.format(ticket.getDate().getTime());
        mailService.sendMail(
                ticket.getOrder().getCustomer().getEmail(),
                subject,
                "<p>Beste " + ticket.getOrder().getCustomer().getFirstName() + " " +
                        ticket.getOrder().getCustomer().getLastName() + "</p><p>" + answer +
                        "</p><p>" + support.getFirstName() + " " + support.getLastName() +
                        "<br />Support MediaShop</p><hr /><p>" + date + "</p><p>" + ticket.getDescription() + "</p>"
        );
        return getTicketDetails(ticket);
    }

    public String supportViewSolvedTickets() {
        Support support = getLoggedinSupport();
        solvedTickets = ticketService.findByStatus(Ticket.Status.SOLVED);
        return "ticketarchive.xhtml?faces-redirect=true";
    }

    public CustomerService getCustomerService() {
        return customerService;
    }

    public void setCustomerService(CustomerService customerService) {
        this.customerService = customerService;
    }

    public EncryptionService getEncryptionService() {
        return encryptionService;
    }

    public void setEncryptionService(EncryptionService encryptionService) {
        this.encryptionService = encryptionService;
    }

    public UserService getUserService() {
        return userService;
    }

    public void setUserService(UserService userService) {
        this.userService = userService;
    }

    public MailService getMailService() {
        return mailService;
    }

    public void setMailService(MailService mailService) {
        this.mailService = mailService;
    }

    public OrderService getOrderService() {
        return orderService;
    }

    public void setOrderService(OrderService orderService) {
        this.orderService = orderService;
    }

    public List<Order> getOrders() {
        return orders;
    }

    public void setOrders(List<Order> orders) {
        this.orders = orders;
    }

    public Order getOrder() {
        return order;
    }

    public void setOrder(Order order) {
        this.order = order;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public TicketService getTicketService() {
        return ticketService;
    }

    public void setTicketService(TicketService ticketService) {
        this.ticketService = ticketService;
    }

    public String getOrderId() {
        return orderId;
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public List<Ticket> getNewTickets() {
        return newTickets;
    }

    public void setNewTickets(List<Ticket> newTickets) {
        this.newTickets = newTickets;
    }

    public List<Ticket> getOpenTickets() {
        return openTickets;
    }

    public void setOpenTickets(List<Ticket> openTickets) {
        this.openTickets = openTickets;
    }

    public List<Ticket> getOnholdTickets() {
        return onholdTickets;
    }

    public void setOnholdTickets(List<Ticket> onholdTickets) {
        this.onholdTickets = onholdTickets;
    }

    public List<Ticket> getSolvedTickets() {
        return solvedTickets;
    }

    public void setSolvedTickets(List<Ticket> solvedTickets) {
        this.solvedTickets = solvedTickets;
    }

    public SupportService getSupportService() {
        return supportService;
    }

    public void setSupportService(SupportService supportService) {
        this.supportService = supportService;
    }

    public Ticket getTicketDetails() {
        return ticketDetails;
    }

    public void setTicketDetails(Ticket ticketDetails) {
        this.ticketDetails = ticketDetails;
    }

    public String getAnswer() {
        return answer;
    }

    public void setAnswer(String answer) {
        this.answer = answer;
    }

    public String getSubject() {
        return subject;
    }

    public void setSubject(String subject) {
        this.subject = subject;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }
}

src/main/java/com/realdolmen/thomasmore/controller/orderController.java
package com.realdolmen.thomasmore.controller;

import com.realdolmen.thomasmore.domain.Customer;
import com.realdolmen.thomasmore.domain.Order;
import com.realdolmen.thomasmore.domain.OrderLine;
import com.realdolmen.thomasmore.domain.OrderStatus;
import com.realdolmen.thomasmore.service.CdService;
import com.realdolmen.thomasmore.service.CustomerService;
import com.realdolmen.thomasmore.service.OrderLineService;
import com.realdolmen.thomasmore.service.OrderService;
import org.primefaces.context.RequestContext;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.core.userdetails.UserDetails;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;
import java.util.ArrayList;
import java.util.List;

@ManagedBean
@SessionScoped
public class orderController {
    @ManagedProperty("#{orderService}")
    private OrderService orderService;

    @ManagedProperty("#{orderLineService}")
    private OrderLineService orderLineService;

    @ManagedProperty("#{customerService}")
    private CustomerService customerService;

    private List<Order> orders = new ArrayList<>();
    private String email;
    private Order order;
    private OrderLine tempDelete;
    private List<OrderLine> orderLinesToDelete;

    private List<Order> ordersHistory = new ArrayList<>();
    private List<Order> ordersOpen = new ArrayList<>();

    private void getAllOrders(){
        orders = orderService.findAllOrders();
    }

    public void getOrdersByCustomer(){
        if(this.email.trim().length() > 0) {
            this.orders = orderService.getOrdersByCustomersEmail(email);
        }
        else{
            email=null;
        }
    }

    public OrderStatus[] getOrderStatuses(){
        return OrderStatus.values();
    }

    public String editOrder(Order order){
        this.orderLinesToDelete = new ArrayList<>();
        this.order = order;
        return "orderForm.xhtml";
    }

    public String deleteOrder(){
        orderLinesToDelete = orderLineService.findOrderLinesByOrders(this.order);
        this.order.getOrderLines().clear();
        deleteOrderLines();
        Order order = orderService.get(this.order.getId());
        orderService.deleteOrder(order);
        orders = orderService.findAllOrders();
        this.order = null;
        return "orders.xhtml";
    }

    private void deleteOrderLines() {
        //set fk in orderline to null
        for(OrderLine orderline : orderLinesToDelete) {
            orderline.setOrder(null);
            orderLineService.saveOrderLine(orderline);
        }
        orderService.saveOrder(order);

        //delete orphan orderlines
        for(OrderLine orderline : orderLinesToDelete) {
            orderLineService.deleteOrderLineById(orderline.getId());
        }
    }

    public String saveOrder(){
        if(orderLinesToDelete.size() > 0) {
            deleteOrderLines();
            if(order.getOrderLines().size() == 0) {
                Order order = orderService.get(this.order.getId());
                orderService.deleteOrder(order);
            }
        }
        else{
            orderService.saveOrder(order);
        }

        tempDelete = null;
        order = null;
        orderLinesToDelete = new ArrayList<>();
        return "orders.xhtml";
    }

    public void deleteOrderLine(){
        orderLinesToDelete.add(tempDelete);
        this.order.getOrderLines().remove(tempDelete);
    }

    //Customer view their orders
    public Customer getLoggedinCustomer() {
        Object principal = SecurityContextHolder.getContext().getAuthentication().getPrincipal();
        String email = ((UserDetails) principal).getUsername();
        Customer customer = customerService.findByEmail(email);
        return customer;
    }
    public String customerOrders(){
        Customer customer = getLoggedinCustomer();
        ordersHistory = orderService.findAllHistoryOrdersByCustomer(customer);
        for (Order orderHistory: ordersHistory) {
            double price = 0;
            for (OrderLine orderLine: orderHistory.getOrderLines()){
                price += (orderLine.getActualPrice() * orderLine.getAmount());
            }
            orderHistory.setPrice(price);
        }
        ordersOpen = orderService.findAllFutureOrdersByCustomer(customer);
        for (Order orderOpen: ordersOpen) {
            double price = 0;
            for (OrderLine orderLine: orderOpen.getOrderLines()){
                price += (orderLine.getActualPrice() * orderLine.getAmount());
            }
            orderOpen.setPrice(price);
        }
        return "/customer/orders.xhtml";
    }



    //getters and setters
    public List<Order> getOrders() {
        if(email==null) {
            getAllOrders();
        }
        return orders;
    }

    public List<OrderLine> getOrderLinesToDelete() {
        return orderLinesToDelete;
    }

    public void setOrderLinesToDelete(List<OrderLine> orderLinesToDelete) {
        this.orderLinesToDelete = orderLinesToDelete;
    }

    public OrderLine getTempDelete() {
        return tempDelete;
    }

    public void setTempDelete(OrderLine tempDelete) {
        this.tempDelete = tempDelete;
    }

    public void setOrders(List<Order> orders) {
        this.orders = orders;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Order getOrder() {
        return order;
    }
    public void setOrder(Order order) {
        this.order = order;
    }

    public List<Order> getOrdersHistory() {
        return ordersHistory;
    }

    public void setOrdersHistory(List<Order> ordersHistory) {
        ordersHistory = ordersHistory;
    }

    public List<Order> getOrdersOpen() {
        return ordersOpen;
    }

    public void setOrdersOpen(List<Order> ordersOpen) {
        ordersOpen = ordersOpen;
    }

    //setters for DI
    public void setOrderService(OrderService orderService) {
        this.orderService = orderService;
    }

    public void setOrderLineService(OrderLineService orderLineService) {
        this.orderLineService = orderLineService;
    }

    public void setCustomerService(CustomerService customerService) {
        this.customerService = customerService;
    }
}

src/main/webapp/support/index.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
>
<h:body>
    <ui:composition template="layout.xhtml">
        <ui:define name="content">
            <div class="container">
                <div class="row padding-top justify-content-center align-items-center">
                    <div class="col-sm-8 text-center">

                        <div class="col-sm-12">
                            <h2>Welkom supportmedewerker</h2>
                        </div>


                        <div class="row">
                            <div class=" col-sm-6 padding-top">
                                <h:button styleClass="font-weight-bold btn btn-outline-dark" style="width:200px; height: 100px"
                                          outcome="orders.xhtml?faces-redirect=true"
                                          value="Bestellingen"/>
                            </div>
                            <div class=" col-sm-6 padding-top">
                                <h:form>
                                    <h:commandButton styleClass="font-weight-bold btn btn-outline-dark"
                                                     style="width:200px; height: 100px"
                                                     action="#{ticketController.supportTicketLists()}"
                                                     value="Tickets"/>
                                </h:form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </ui:define>
    </ui:composition>
</h:body>
</html>

src/main/webapp/support/layout.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">
<h:head>
    <f:facet name="first">
        <meta charset="utf-8"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>

        <title>primestrap</title>
    </f:facet>
    <f:facet name="middle">
        <h:outputStylesheet name="css/bootstrap.min.css"/>
        <h:outputStylesheet name="css/style.css" />

    </f:facet>
    <f:facet name="last">
        <h:outputScript name="js/webshop.js" />
        <script src="https://use.fontawesome.com/b8fb62ff67.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
        <h:outputScript name="js/bootstrap.min.js" />
    </f:facet>
</h:head>
<h:body>

    <ui:include src="supportHeader.xhtml"/>

    <ui:insert name="content">

    </ui:insert>
</h:body>
</html>

src/main/webapp/support/orderForm.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:c="http://java.sun.com/jsp/jstl/core" template="layout.xhtml">


<ui:define name="content">
    <div class="container">
        <div class="row padding-top" >
            <div class="col-10 col-md-8">
                <h:form >
                    <div class="form-group">
                        <h:outputLabel value="Leverdatum: " for="Deliverdate" />
                        <h:inputText id="Deliverdate"  value="#{orderController.order.deliveryDate}" required="true" requiredMessage="Leverdatum is verplicht"
                                     converterMessage="Formaat is dd-mm-yyyy" title="Leverdatum" class="form-control">
                            <f:convertDateTime pattern="dd-MM-yyyy" timeZone="GMT+1" />
                        </h:inputText>
                        <h:message for="Deliverdate" class="error"/>
                    </div>

                    <div class="form-group">
                        <h:outputLabel value="Status van de bestelling: " for="status" />
                        <h:selectOneMenu value="#{orderController.order.orderStatus}" id="status" required="true" requiredMessage="Status is verplicht" class="form-control">
                            <f:selectItems value="#{orderController.orderStatuses}" />
                        </h:selectOneMenu>
                        <h:message for="status" class="error"/>
                    </div>

                    <div class="form-group" id="content">

                        <h3>Bestelde producten</h3>
                        <ui:repeat value="#{orderController.order.orderLines}" var="orderline" id="products">
                            <li class="list-group-item" id="#{orderline.id}">
                               <h:outputText value="#{orderline.product.name}"/>
                                <h:inputText id="amount" converterMessage="Alleen maar getallen toegestaan" class="form-control amountInput" value="#{orderline.amount}" type="number" required="true" requiredMessage="Je moet een aantal ingeven"/>
                                <h:message for="amount" class="error"/>

                                <h:commandLink action="#{orderController.setTempDelete(orderline)}">
                                    <f:ajax render="content:products" />
                                    <i data-id="#{orderline.id}" class="productDeleteIcon fa fa-trash-o"  aria-hidden="true"></i>
                                </h:commandLink>
                            </li>
                        </ui:repeat>
                    </div>

                    <div class="form-group">
                        <h:commandButton action="#{orderController.saveOrder()}" value="Opslaan" class="btn btn-primary"/>
                        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal">
                            Verwijder
                        </button>
                    </div>
                </h:form>
            </div>
        </div>

        <!-- Modal -->
        <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="deleteModalLabel">Ben je zeker?</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">X</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        Ben je zeker dat je deze volledige bestelling wil verwijderen?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <h:form>
                            <input type="hidden" name="#{_csrf.parameterName}" value="#{_csrf.token}"/>
                            <h:commandButton action="#{orderController.deleteOrder()}" value="Verwijder" class="btn btn-danger"/>
                        </h:form>
                    </div>
                </div>
            </div>
        </div>

        <!-- product delete Modal -->
        <div class="modal fade" id="productDelete" tabindex="-1" role="dialog" aria-labelledby="productDeleteLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="productDeleteLabel">Ben je zeker?</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">X</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        Ben je zeker dat je dit product uit de bestelling wil verwijderen?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <h:form>
                            <h:commandButton action="#{orderController.deleteOrderLine()}" value="Verwijder" class="btn btn-danger" id="productDeleteButton"/>
                        </h:form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</ui:define>
</ui:composition>

src/main/webapp/support/orders.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:c="http://java.sun.com/jsp/jstl/core"
                xmlns:p="http://primefaces.org/ui"
                xmlns:ui="http://java.sun.com/jsf/facelets" template="layout.xhtml">

    <ui:define name="content">
        <div class="container">
            <div class="row padding-top">
                <div class="col-12 text-center">
                    <h1>Bestellingen</h1>
                </div>

                <div class="col-12">
                    <h:form>
                        <input type="hidden" name="#{_csrf.parameterName}" value="#{_csrf.token}"/>

                        <div class="row padding-top padding-bottom justify-content-md-center">
                            <div class="col-sm-10 col-md-4">
                                <div class="form-group">
                                    <h:inputText id="email" value="#{orderController.email}" title="email" class="form-control" />
                                </div>
                            </div>

                            <div class="col-sm-12 col-md-2 text-center">
                                <div class="form-group">
                                    <h:commandButton action="#{orderController.getOrdersByCustomer()}" value="Zoek op e-mail" class="btn btn-primary"/>
                                </div>
                            </div>
                        </div>
                    </h:form>
                </div>

                <div class="col-12 text-center">
                    <div>
                        <p:dataList value="#{orderController.orders}" var="order" type="unordered" itemType="none" paginator="true" rows="30" styleClass="paginated">
                            <h:form>
                                <input type="hidden" name="#{_csrf.parameterName}" value="#{_csrf.token}"/>
                                <div>
                                    <h:commandLink value="#{order.orderDate} -- #{order.customer.firstName} #{order.customer.lastName}" action="#{orderController.editOrder(order)}"/>
                                </div>
                            </h:form>
                        </p:dataList>
                    </div>
                </div>
            </div>
        </div>
    </ui:define>
</ui:composition>

src/main/webapp/support/supportHeader.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                xmlns:ui="http://java.sun.com/jsf/facelets">

    <nav class="navbar navbar-expand-lg  navbar-dark bg-dark">
        <p:commandLink styleClass="navbar-brand" value="MediaShop" action="#{adminController.backToWebshop()}" />
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <h:form >
                <input type="hidden" name="#{_csrf.parameterName}" value="#{_csrf.token}"/>
                <ul class="navbar-nav bg-dark">
                    <li class="nav-item">
                        <h:link value="Bestellingen" outcome="orders.xhtml?faces-redirect=true" styleClass="nav-link"/>
                    </li>
                    <li class="nav-item">
                        <p:commandLink styleClass="nav-link" value="Tickets" action="#{ticketController.supportTicketLists()}" />
                    </li>
                </ul>
            </h:form>
        </div>
    </nav>
</ui:composition>