src/main/java/com/realdolmen/thomasmore/domain/Address.java
package com.realdolmen.thomasmore.domain;

import javax.persistence.Embeddable;

@Embeddable
public class Address {
    private String street;
    private String postalCode;
    private String city;

    public Address() {
        street="";
        postalCode="";
        city="";
    }

    public Address(String street, String postalCode, String city) {
        this.street = street;
        this.postalCode = postalCode;
        this.city = city;
    }

    public String getStreet() {
        return street;
    }

    public void setStreet(String street) {
        this.street = street;
    }

    public String getPostalCode() {
        return postalCode;
    }

    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }
}

src/main/java/com/realdolmen/thomasmore/domain/Admin.java
package com.realdolmen.thomasmore.domain;

import javax.persistence.DiscriminatorValue;
import javax.persistence.Entity;

@Entity
@DiscriminatorValue("Admin")
public class Admin extends User{

    public Admin() {
    }

    public Admin(String email, String firstName, String lastName, String password) {
        super(email, firstName, lastName, password);
    }
}

src/main/java/com/realdolmen/thomasmore/domain/Cd.java
package com.realdolmen.thomasmore.domain;


import javax.persistence.*;
import java.io.Serializable;
import java.util.Date;
import java.util.GregorianCalendar;

@Entity
public class Cd extends Product implements Serializable{
    private String publisher;
    private String artists;
    @Temporal(TemporalType.DATE)
    private Date releaseDate = new Date();
    private String genres;
    private String songs;

    public Cd() {
        super();
    }

    public Cd(String publisher, String artists, Date releaseDate, String genres) {
        this.publisher = publisher;
        this.artists = artists;
        this.releaseDate = releaseDate;
        this.genres = genres;
    }

    public Cd(String code, String name, double price, String description, int stock, String publisher, String artists, Date releaseDate, String genres) {
        super(code, name, price, description,stock);
        this.publisher = publisher;
        this.artists = artists;
        this.releaseDate = releaseDate;
        this.genres = genres;
    }

    public Cd(String code, String name, double price, String description,int stock) {
        super(code, name, price, description,stock);
    }

    @Override
    public String getType() {
        return "cd";
    }

    public String getPublisher() {
        return publisher;
    }

    public void setPublisher(String publisher) {
        this.publisher = publisher;
    }

    public String getArtists() {
        return artists;
    }

    public void setArtists(String artists) {
        this.artists = artists;
    }

    public Date getReleaseDate() {
        return releaseDate;
    }

    public void setReleaseDate(Date releaseDate) {
        this.releaseDate = releaseDate;
    }

    public String getGenres() {
        return genres;
    }

    public void setGenres(String genres) {
        this.genres = genres;
    }

    public String getSongs() {
        return songs;
    }

    public void setSongs(String songs) {
        this.songs = songs;
    }
}

src/main/java/com/realdolmen/thomasmore/domain/Customer.java
package com.realdolmen.thomasmore.domain;

import javax.persistence.*;
import java.util.List;

@Entity
@DiscriminatorValue("Customer")
public class Customer extends User {

    private boolean active;

    @Embedded
    private Address billingAddress;
    @AttributeOverrides({
            @AttributeOverride(name = "street", column = @Column(name = "billingStreet")),
            @AttributeOverride(name = "postalCode", column = @Column(name = "billingPostalCode")),
            @AttributeOverride(name = "city", column = @Column(name = "billingCity"))
    })

    @Embedded
    private Address deliveryAddress1;
    @AttributeOverrides({
            @AttributeOverride(name = "street", column = @Column(name = "deliveryStreet1")),
            @AttributeOverride(name = "postalCode", column = @Column(name = "deliveryPostalCode1")),
            @AttributeOverride(name = "city", column = @Column(name = "deliveryCity1"))
    })

    @Embedded
    private  Address deliveryAddress2;
    @AttributeOverrides({
            @AttributeOverride(name = "street", column = @Column(name = "deliveryStreet2")),
            @AttributeOverride(name = "postalCode", column = @Column(name = "deliveryPostalCode2")),
            @AttributeOverride(name = "city", column = @Column(name = "deliveryCity2"))
    })

    @OneToMany(mappedBy = "customer", cascade = {CascadeType.PERSIST, CascadeType.REMOVE})
    private List<Order> orders;

    @ManyToMany(cascade = {CascadeType.PERSIST, CascadeType.REMOVE})
    @JoinTable(name="CUSTOMER_PAYMENTMETHOD")
    private List<PaymentMethod> paymentMethods;

    public Customer() {
    }

    public Customer(String email, String firstName, String lastName, String password) {
        super(email, firstName, lastName, password);
    }

    public Customer(String email, String firstName, String lastName, Address billingAddress, Address deliveryAddress1, Address deliveryAddress2, String password) {
        super(email, firstName, lastName, password);
        this.billingAddress = billingAddress;
        this.deliveryAddress1 = deliveryAddress1;
        this.deliveryAddress2 = deliveryAddress2;
    }

    public Address getBillingAddress() {
        return billingAddress;
    }

    public void setBillingAddress(Address billingAddress) {
        this.billingAddress = billingAddress;
    }

    public Address getDeliveryAddress1() {
        return deliveryAddress1;
    }

    public void setDeliveryAddress1(Address deliveryAddress1) {
        this.deliveryAddress1 = deliveryAddress1;
    }

    public Address getDeliveryAddress2() {
        return deliveryAddress2;
    }

    public void setDeliveryAddress2(Address deliveryAddress2) {
        this.deliveryAddress2 = deliveryAddress2;
    }

    public List<Order> getOrders() {
        return orders;
    }

    public void setOrders(List<Order> orders) {
        this.orders = orders;
    }

    public List<PaymentMethod> getPaymentMethods() {
        return paymentMethods;
    }

    public void setPaymentMethods(List<PaymentMethod> paymentMethods) {
        this.paymentMethods = paymentMethods;
    }

    public boolean isActive() {
        return active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }
}

src/main/java/com/realdolmen/thomasmore/domain/Image.java
package com.realdolmen.thomasmore.domain;

import javax.persistence.*;

@Entity
public class Image {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    @Transient
    private String host = "http://localhost:5000/images/";

    @Transient
    private String baseImage = "%d.jpg";

    @OneToOne
    private Product product;

    public String getPath(){
        return host + String.format(baseImage, product.getId());
    }

    public String getSimplePath(){
        return String.format(baseImage, product.getId());
    }

    public Product getProduct() {
        return product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }
}

src/main/java/com/realdolmen/thomasmore/domain/OrderStatus.java
package com.realdolmen.thomasmore.domain;

public enum OrderStatus {
    PROCESSING, ORDERED, IN_TRANSIT, DELIVERED
}

src/main/java/com/realdolmen/thomasmore/domain/Product.java
package com.realdolmen.thomasmore.domain;



import com.realdolmen.thomasmore.service.ImageService;
import javax.persistence.*;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

@Inheritance(strategy = InheritanceType.JOINED)
@Entity
public abstract class Product implements Serializable{

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private String code;
    private String name;
    private double price;
    private String description;
    private int stock;
    private boolean deleted;


    @OneToMany(mappedBy = "product", cascade = {CascadeType.PERSIST, CascadeType.MERGE  })
    private List<OrderLine> orderLines;

    @OneToMany(mappedBy = "product", cascade = {CascadeType.PERSIST, CascadeType.REMOVE}, fetch = FetchType.EAGER)
    private List<Review> reviews;

    @OneToOne(cascade = {CascadeType.ALL})
    private Image image;

    public String getImagePath(){
        if(image != null)
            return image.getPath();

        return "";
    }

    public Image getImage() {
        return image;
    }

    public void setImage(Image image) {
        this.image = image;
    }

    /*public List<Image> getImages() {
            return images;
        }

        public void setImages(List<Image> images) {
            this.images = images;
        }

        public void addImage(Image image){
            this.images.add(image);
        }*/
    public Product() {
        reviews = new ArrayList<>();
    }

    public Product(String code, String name, double price, String description, int stock) {
        reviews = new ArrayList<>();
        this.code = code;
        this.name = name;
        this.price = price;
        this.description = description;
        this.stock = stock;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public double getPrice() {
        return price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public int getStock() {
        return stock;
    }

    public void setStock(int stock) {
        this.stock = stock;
    }

    public boolean isDeleted() {
        return deleted;
    }

    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }

    public List<OrderLine> getOrderLines() {
        return orderLines;
    }

    public void setOrderLines(List<OrderLine> orderLines) {
        this.orderLines = orderLines;
    }

    public List<Review> getReviews() {
        return reviews;
    }

    public void setReviews(List<Review> reviews) {
        this.reviews = reviews;
    }

    public void addReview(Review review){
        this.reviews.add(review);
    }

    public double getRating(){
        double sum = 0;

        for(Review review: this.reviews) sum+= review.getRating();

        if (sum != 0){
            return (double)Math.round((sum / this.reviews.size())*100.0)/100.0 ;
        } else {
            return 0;
        }
    }

    public int getRatingInt(){
        int sum = 0;

        for(Review review: this.reviews) sum+= review.getRating();

        if (sum != 0){
            return sum / this.reviews.size() ;
        } else {
            return 0;
        }


    }

    public List<String> getImageNames(){
        List<String> images = new ArrayList<>();
        images.add(this.getImagePath());
        return images;
    }

    public abstract String getType();

    public void deleteImage(Image image){
        ImageService imageService = new ImageService();
        if(imageService.deleteImage(image)){
        }
    }

}

src/main/java/com/realdolmen/thomasmore/domain/ShoppingItem.java
package com.realdolmen.thomasmore.domain;

public class ShoppingItem{
    private Product product;
    private int amount;

    public ShoppingItem(Product product, int amount) {
        this.product = product;
        this.amount = amount;
    }

    public Double getSubTotal(){
        return this.product.getPrice() * this.amount;
    }

    public void add(int amount){
        this.amount += amount;
    }

    public Product getProduct() {
        return product;
    }

    public int getAmount() {
        return amount;
    }

    public void setAmount(int amount){
        this.amount = amount;
    }
}

src/main/java/com/realdolmen/thomasmore/domain/Support.java
package com.realdolmen.thomasmore.domain;

import javax.persistence.DiscriminatorValue;
import javax.persistence.Entity;
import javax.persistence.OneToMany;
import java.util.ArrayList;
import java.util.List;

@Entity
@DiscriminatorValue("Support")
public class Support extends User {

    public Support() {
    }

    public Support(String email, String firstName, String lastName, String password) {
        super(email, firstName, lastName, password);
    }

    @OneToMany(mappedBy = "support")
    private List<Ticket> tickets = new ArrayList<Ticket>();

    public List<Ticket> getTickets() {
        return tickets;
    }

    public void setTickets(List<Ticket> tickets) {
        this.tickets = tickets;
    }
}

src/main/java/com/realdolmen/thomasmore/controller/CartController.java
package com.realdolmen.thomasmore.controller;

import com.realdolmen.thomasmore.domain.Product;
import com.realdolmen.thomasmore.domain.ShoppingCart;
import com.realdolmen.thomasmore.domain.ShoppingItem;
import com.realdolmen.thomasmore.service.ImageService;
import javassist.NotFoundException;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;
import java.util.ArrayList;

@ManagedBean
@SessionScoped
public class CartController {
    ShoppingCart shoppingCart;

    ArrayList<ShoppingItem> items;

    boolean isEmtpy;

    public boolean getIsEmpty() {
        this.setShoppingCart(new ShoppingCart());
        return (shoppingCart.getItemCount() == 0);
    }

    public ArrayList<ShoppingItem> getItems() {
        this.setShoppingCart(new ShoppingCart());
        return this.shoppingCart.getItems();
    }

    public ShoppingCart getShoppingCart() {
        this.setShoppingCart(new ShoppingCart());
        return shoppingCart;
    }

    public void setShoppingCart(ShoppingCart shoppingCart) {
        if(this.shoppingCart == null)
            this.shoppingCart = shoppingCart;
    }

    public void AddProduct(Product product, int amount){
        shoppingCart.addProduct(product, amount);
    }

    public void RemoveProduct(Product product){
        shoppingCart.removeProduct(product);
    }

    public void ChangeAmount(Product product, int amount){
        try {
            shoppingCart.changeProductAmount(product, amount);
        } catch (NotFoundException nfe) {
            System.out.println(nfe.getMessage());
        }
    }
}

src/main/java/com/realdolmen/thomasmore/controller/CustomerController.java
package com.realdolmen.thomasmore.controller;

import com.realdolmen.thomasmore.domain.Address;
import com.realdolmen.thomasmore.domain.Customer;
import com.realdolmen.thomasmore.security.UserSession;
import com.realdolmen.thomasmore.service.CustomerService;

import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;

@ManagedBean
@ViewScoped
public class CustomerController {
    private Customer customer;
    private String newPassword;
    private String newPassword2;

    @ManagedProperty("#{userSession}")
    private UserSession userSession;

    @ManagedProperty("#{customerService}")
    private CustomerService customerService;

    @PostConstruct
    public void init(){
        customer = customerService.findById(userSession.getUser().getId());
        if (customer.getBillingAddress() == null) customer.setBillingAddress(new Address());
        if (customer.getDeliveryAddress1() == null) customer.setDeliveryAddress1(new Address());
        if (customer.getDeliveryAddress2() == null) customer.setDeliveryAddress2(new Address());
        newPassword = "";
        newPassword2 = "";
    }


    public Customer getCustomer() {
        return customer;
    }

    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    public void saveCustomer(){
        customerService.saveCustomer(customer);
        userSession.setUser(customer);
        FacesContext context = FacesContext.getCurrentInstance();
        context.addMessage(null, new FacesMessage("Profiel geüpdatet") );
    }


    public String getNewPassword() {
        return newPassword;
    }

    public void setNewPassword(String newPassword) {
        this.newPassword = newPassword;
    }

    public String getNewPassword2() {
        return newPassword2;
    }

    public void setNewPassword2(String newPassword2) {
        this.newPassword2 = newPassword2;
    }

    public void updateCustomerPassword(){
        customer.setPassword(newPassword);
        customerService.updatePassword(customer);
        FacesContext context = FacesContext.getCurrentInstance();
        context.addMessage(null, new FacesMessage("Wachtwoord geüpdatet") );
        newPassword = "";
        newPassword2 = "";
    }


    public void setUserSession(UserSession userSession) {
        this.userSession = userSession;
    }

    public CustomerService getCustomerService() {
        return customerService;
    }

    public void setCustomerService(CustomerService customerService) {
        this.customerService = customerService;
    }
}

src/main/webapp/activateaccount.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                xmlns:ui="http://java.sun.com/jsf/facelets" template="layout.xhtml">
    <ui:define name="content">
        <div class="container">
            <div class="row padding-top">
                <div class="col-sm-12 text-center">
                    <h:form id="form">
                        <input type="hidden" name="token" value="#{param['token']}"/>
                        <h:commandButton id="submit" value="Activeer" action="#{registerController.activateAccount()}"
                                         update="@form" style="display: none"/>
                    </h:form>
                </div>
            </div>
        </div>
        <script>
            document.getElementById('form:submit').click();
        </script>
    </ui:define>
</ui:composition>

src/main/webapp/cart.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                xmlns:ui="http://java.sun.com/jsf/facelets" template="/layout.xhtml"
                xmlns:c="http://java.sun.com/jsp/jstl/core">
    <ui:define name="content">
        <h:form>
        <div class="container">
            <div class="card">
            <div class="card-header">
            <div class="row">
            <div class="col-sm-6 text-center">
                <h:outputText value="Aantal producten: #{cartController.shoppingCart.itemCount}"/>
            </div>
                <div class="col-sm-6 text-center">
                    <h:outputText value="Totaal prijs: €#{cartController.shoppingCart.totalPrice}"/>
                </div>
            </div>
            </div>
                <div class="card-body">
                    <c:if test="#{cartController.isEmpty}">
                        <h1>Uw winkelwagen is leeg.</h1>
                    </c:if>
                    <c:if test="#{!cartController.isEmpty}">
                        <p:dataList value="#{cartController.items}" var="item" type="unordered" itemType="none" paginator="false">
                            <f:facet name="header">Winkelmandje</f:facet>
                            <hr></hr>
                            <div class="row">
                                <div class="col-sm-4">
                                    <img src="#{item.product.imagePath}" alt="afbeelding" height="100px" />
                                </div>
                                <div class="col-sm-4">
                                    <div><h:outputLink
                                            value="${request.contextPath}/productdetail.xhtml?productId=${item.product.id}"
                                            style="color: #007bff">
                                        #{item.product.name}
                                    </h:outputLink>
                                    </div>
                                    <div>
                                        <h:outputText value="€#{item.product.price}"/>
                                    </div>
                                    <div>
                                        <h:outputText value="Aantal: #{item.amount}"/>
                                    </div>
                                </div>
                                <div class="col-sm-2">
                                    <div>
                                        <h:outputText value="Subtotaal: €#{item.subTotal}"/>
                                    </div>
                                </div>
                            </div>
                        </p:dataList>
                    </c:if>
                </div>
                <div class="form-group">
                    <c:if test="#{authController.userLoggedIn()}">
                        <h:commandButton action="#{paymentController.createPayment(cartController.shoppingCart.toOrder())}" value="Bestel" class="btn btn-primary"/>
                    </c:if>
                    <c:if test="#{!authController.userLoggedIn()}">
                        <h:button styleClass="btn btn-primary" value="login in" action="/login.xhtml?faces-redirect=true" />
                    </c:if>
                </div>
            </div>
        </div>
        </h:form>
    </ui:define>
</ui:composition>

src/main/webapp/header.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:c="http://java.sun.com/jsp/jstl/core">

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <h:link value="MediaShop" outcome="/index.xhtml" styleClass="navbar-brand"/>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">

            <ul class="navbar-nav ml-md-auto">
                <li class="nav-item">
                    <h:link value="Winkelmandje" outcome="/cart.xhtml" styleClass="nav-link" />
                </li>
                <c:if test="#{authController.userLoggedIn()}">
                    <c:if test="#{authController.canAccessAdmin()}">
                        <li class="nav-item">
                            <h:link value="Admin" outcome="/admin/index.xhtml" styleClass="nav-link"/>
                        </li>
                    </c:if>
                    <c:if test="#{authController.canAccessSupport()}">
                        <li class="nav-item">
                            <h:link value="Support" outcome="/support/index.xhtml" styleClass="nav-link"/>
                        </li>
                    </c:if>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarUserDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <h:outputText id="headerUserName" value="#{userSession.user.firstName} #{userSession.user.lastName}" />
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarUserDropdown">
                            <ui:fragment rendered="#{authController.canAccessCustomer()}">
                                <h:outputLink value="${request.contextPath}/customer/profile.xhtml" styleClass="dropdown-item">Profiel</h:outputLink>
                                <h:form>
                                    <h:outputLink value="${request.contextPath}/customer/redirectticket.xhtml" styleClass="dropdown-item">Support</h:outputLink>
                                    <h:outputLink value="${request.contextPath}/customer/redirectorders.xhtml" styleClass="dropdown-item">Bestellingen</h:outputLink>
                                </h:form>
                            </ui:fragment>
                            <h:outputLink value="${request.contextPath}/logout" styleClass="dropdown-item">Uitloggen</h:outputLink>
                        </div>
                    </li>
                </c:if>
                <c:if test="#{!authController.userLoggedIn()}">
                    <li class="nav-item">
                        <h:link value="Registreer" outcome="/register.xhtml" styleClass="nav-link"/>
                    </li>
                    <li class="nav-item">
                        <h:link value="Login" outcome="/login.xhtml" styleClass="nav-link"/>
                    </li>
                </c:if>
            </ul>
        </div>
    </nav>
</ui:composition>

src/main/webapp/layout.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
             xmlns:ui="http://java.sun.com/jsf/facelets"
             xmlns:h="http://java.sun.com/jsf/html"
             xmlns:f="http://java.sun.com/jsf/core"
             xmlns:p="http://primefaces.org/ui">
<h:head>
    <f:facet name="first">
        <meta charset="utf-8"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>

        <title>primestrap</title>
    </f:facet>
    <f:facet name="middle">
        <h:outputStylesheet name="css/bootstrap.min.css"/>
        <h:outputStylesheet name="css/style.css" />

    </f:facet>
    <f:facet name="last">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
    </f:facet>
</h:head>
<h:body>

    <ui:include src="header.xhtml"/>

    <ui:insert name="content">
    </ui:insert>
</h:body>
</html>

src/main/webapp/login.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                xmlns:ui="http://java.sun.com/jsf/facelets" template="layout.xhtml">
    <ui:define name="content">
    <div class="container">
        <div class="row padding-top">
            <div class="col-sm-12 text-center">
                <h3>Login</h3>

                <h:form prependId="false" method="POST" id="loginForm">
                    <input type="hidden" name="#{_csrf.parameterName}" value="#{_csrf.token}"/>
                    <p:growl id="messages"/>
                    <h:message class="error" for="errorMessage" id="errorMessage"/>
                    <div class="form-group">
                        <p:outputLabel value="E-mail:"/>
                        <h:inputText id="username" name="username" class="form-control"/>
                    </div>

                    <div class="form-group">
                        <p:outputLabel value="Password:"/>
                        <h:inputSecret  id="password" name="password" class="form-control"/>
                    </div>
                    <h:commandButton value="Login" class="btn btn-primary" action="/login.xhtml" ajax="false"/>
                </h:form>​
            </div>
        </div>
    </div>
    </ui:define>
</ui:composition>

src/main/webapp/logintest.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">
<h:head>
    <script name="jquery/jquery.js" library="primefaces"></script>
    <title>Register Employee</title>
</h:head>
<h:body>
    <h1>Login test</h1>
    <!--  knop -->
    <h:form>
        <input type="hidden" name="#{_csrf.parameterName}" value="#{_csrf.token}"/>
        <p:commandButton value="maak test objecten aan" action="#{testController.makeObjects}" ajax="false" styleClass="ui-priority-primary" />
        <p:commandButton value="maak producten aan" action="#{testController.makeProducts}" ajax="false" styleClass="ui-priority-primary" />
        <p:commandButton value="extra order" action="#{testController.extraOrder}" ajax="false" styleClass="ui-priority-primary" />
        <p:commandButton value="test payment service" action="#{paymentController.testPayment}" ajax="false" styleClass="ui-priority-primary" />
    </h:form>

    <h:form  prependId="false" method="POST">
        <input type="hidden" name="#{_csrf.parameterName}" value="#{_csrf.token}"/>
        <p:commandButton value="Login" action="login.xhtml"/>
    </h:form>

    <h:outputLink value="${request.contextPath}/logout">Logout</h:outputLink>

</h:body>
</html>

src/main/webapp/registerconfirmationpage.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                xmlns:ui="http://java.sun.com/jsf/facelets" template="layout.xhtml">
    <ui:define name="content">
        <div class="container">
            <div class="row padding-top">
                <div class="col-sm-12 text-center">
                    <h:outputText id="message" value="#{registerController.message}"/>
                </div>
            </div>
        </div>
    </ui:define>
</ui:composition>

src/main/webapp/resetpasswordconfirmationpage.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                xmlns:ui="http://java.sun.com/jsf/facelets" template="layout.xhtml">
<ui:define name="content">
    <div class="container">
        <div class="row padding-top">
            <div class="col-sm-12 text-center">
                <h:outputText id="message" value="#{resetPasswordController.message}"/>
            </div>
        </div>
    </div>
</ui:define>
</ui:composition>